### ISSUE TITLE
No Maven release

### ISSUE THREAD

**Issue by frapontillo** [infogram/infogram-java#5]
Is this module ready to be used in production? How should we consider it?

**Comment by martinsb** [comment]
This module hasn't been tested excessively, since infogr.am does not use Java in production. It is a very thin wrapper around infogr.am REST API (https://developers.infogr.am/rest/), therefore there are not many possible points of failure in the module itself.
I think, provided you need to work with infogr.am API, you should try it out and see if it works for you or you'd be better off writing your own library. Anyway, we'd be happy to receive any feedback. Many thanks.

**Comment by frapontillo** [comment]
Generally speaking, I'd better have a proper RESTful API, that is accepting application/json for your content, not url-encoded values (which are a mess to test and debug). But that's a server issue I think you should discuss and re-evaluate.
